"""Tabela local de alimentos comuns (valores aproximados por 100 g/ml) com
porções típicas — para registar refeições sem precisar de saber os nutrientes.

Valores baseados em tabelas de composição de alimentos (INSA/USDA), arredondados.
Cada porção é (etiqueta, gramas). Onde um nutriente não é fonte relevante, fica 0.
"""
from core import i18n
from core.nutrients import CAMPOS_NUTRIENTES

_CAT_EN = {
    "Pão e cereais": "Bread & cereals", "Proteínas": "Proteins", "Lacticínios": "Dairy",
    "Leguminosas": "Legumes", "Sopas e pratos": "Soups & dishes", "Fruta": "Fruit",
    "Vegetais": "Vegetables", "Molhos e temperos": "Sauces & seasonings",
    "Gorduras e frutos secos": "Fats & nuts", "Doces e snacks": "Sweets & snacks",
    "Bebidas": "Drinks", "⭐ Os meus": "⭐ Mine",
}


def categoria_nome(cat: str) -> str:
    return _CAT_EN.get(cat, cat) if i18n.idioma() == "en" else cat


# Tradução de nomes GENÉRICOS (pratos/sobremesas tipicamente PT ficam sem entrada → PT)
_NOMES_EN = {
    "Pão de forma branco": "White sliced bread", "Pão integral": "Wholegrain bread",
    "Pão (papo-seco/carcaça)": "Bread roll", "Tosta / pão torrado": "Toast",
    "Arroz branco cozido": "White rice (cooked)", "Massa cozida": "Pasta (cooked)",
    "Aveia (flocos)": "Oats", "Cereais de pequeno-almoço (flocos de milho)": "Breakfast cereal",
    "Batata cozida": "Boiled potato", "Batata frita (caseira)": "Fries (homemade)",
    "Broa de milho": "Corn bread", "Tosta mista": "Ham & cheese toastie",
    "Ovo": "Egg", "Peito de frango grelhado": "Grilled chicken breast", "Bife de vaca": "Beef steak",
    "Carne de porco (lombo)": "Pork loin", "Salmão": "Salmon", "Atum em água (lata)": "Canned tuna",
    "Bacalhau cozido": "Cod (boiled)", "Sardinha": "Sardines", "Camarão": "Shrimp",
    "Fiambre de frango": "Chicken ham", "Hambúrguer de vaca": "Beef burger",
    "Hambúrguer de porco": "Pork burger",
    "Leite meio-gordo": "Semi-skimmed milk", "Iogurte natural": "Plain yogurt",
    "Queijo de cabra": "Goat cheese", "Queijo fresco": "Fresh cheese", "Queijo mozzarella": "Mozzarella",
    "Queijo parmesão (ralado)": "Parmesan (grated)", "Queijo creme (tipo Philadelphia)": "Cream cheese",
    "Iogurte grego": "Greek yogurt", "Iogurte magro": "Low-fat yogurt", "Kefir": "Kefir",
    "Leite gordo": "Whole milk", "Leite magro": "Skimmed milk", "Bebida de aveia": "Oat drink",
    "Natas (para cozinhar)": "Cooking cream", "Queijo de cabra ": "Goat cheese",
    "Feijão cozido": "Beans (cooked)", "Grão-de-bico cozido": "Chickpeas (cooked)",
    "Lentilhas cozidas": "Lentils (cooked)",
    "Banana": "Banana", "Maçã": "Apple", "Laranja": "Orange", "Pera": "Pear",
    "Morangos": "Strawberries", "Uvas": "Grapes", "Kiwi": "Kiwi", "Melancia": "Watermelon",
    "Brócolos cozidos": "Broccoli (cooked)", "Espinafres cozidos": "Spinach (cooked)",
    "Cenoura": "Carrot", "Alface": "Lettuce", "Tomate": "Tomato", "Couve cozida": "Cabbage (cooked)",
    "Sopa de legumes": "Vegetable soup", "Cebola": "Onion", "Alho": "Garlic", "Pimento": "Bell pepper",
    "Maionese": "Mayonnaise", "Maionese light": "Light mayonnaise", "Ketchup": "Ketchup",
    "Mostarda": "Mustard", "Molho barbecue": "Barbecue sauce", "Molho béchamel": "Béchamel sauce",
    "Molho de soja": "Soy sauce", "Pesto": "Pesto", "Molho de tomate (polpa)": "Tomato sauce",
    "Vinagre": "Vinegar",
    "Azeite": "Olive oil", "Manteiga": "Butter", "Amêndoas": "Almonds", "Nozes": "Walnuts",
    "Abacate": "Avocado",
    "Creme de legumes": "Vegetable cream soup", "Sopa de abóbora": "Pumpkin soup",
    "Sopa de feijão verde": "Green bean soup", "Caldeirada de peixe": "Fish stew",
    "Lasanha": "Lasagna", "Esparguete à bolonhesa": "Spaghetti bolognese",
    "Caril de frango": "Chicken curry", "Frango assado": "Roast chicken",
    "Omelete (2 ovos)": "Omelette (2 eggs)",
    "Chocolate de leite": "Milk chocolate", "Bolacha Maria": "Plain biscuit",
    "Batatas fritas de pacote": "Crisps", "Croissant": "Croissant", "Pizza (queijo)": "Pizza (cheese)",
    "Gelado (baunilha)": "Ice cream (vanilla)", "Bolo de chocolate": "Chocolate cake",
    "Mousse de chocolate": "Chocolate mousse", "Pudim flan": "Crème caramel",
    "Tarte de maçã": "Apple pie",
    "Café expresso": "Espresso", "Café com leite": "Coffee with milk",
    "Sumo de laranja natural": "Fresh orange juice", "Refrigerante (cola)": "Soft drink (cola)",
    "Vinho tinto": "Red wine", "Cerveja": "Beer", "Água": "Water", "Mel": "Honey",
}


def nome(nome_pt: str) -> str:
    """Nome do alimento no idioma ativo. Pratos típicos sem tradução ficam em PT."""
    return _NOMES_EN.get(nome_pt, nome_pt) if i18n.idioma() == "en" else nome_pt


def _f(nome: str, categoria: str, porcoes: list[tuple[str, int]], **nutrientes) -> dict:
    base = {k: 0.0 for k in CAMPOS_NUTRIENTES}
    base.update(nutrientes)
    return {"nome": nome, "categoria": categoria, "porcoes": porcoes, "por_100g": base}


# Ordem em que as categorias aparecem na app
CATEGORIAS = [
    "Pão e cereais", "Proteínas", "Lacticínios", "Leguminosas", "Sopas e pratos",
    "Fruta", "Vegetais", "Molhos e temperos", "Gorduras e frutos secos",
    "Doces e snacks", "Bebidas",
]

ALIMENTOS = [
    # ---------- Pão e cereais ----------
    _f("Pão de forma branco", "Pão e cereais", [("1 fatia", 28), ("2 fatias", 56)],
       kcal=265, proteina_g=9, hidratos_g=49, gordura_g=3.2, gordura_saturada_g=0.7,
       fibra_g=2.7, acucar_g=5, sodio_mg=490, ferro_mg=3.6, magnesio_mg=25, calcio_mg=150,
       vit_b1_mg=0.5, vit_b3_mg=4, folato_ug=130),
    _f("Pão integral", "Pão e cereais", [("1 fatia", 32), ("2 fatias", 64)],
       kcal=247, proteina_g=13, hidratos_g=41, gordura_g=3.4, gordura_saturada_g=0.7,
       fibra_g=7, acucar_g=6, sodio_mg=450, ferro_mg=2.5, magnesio_mg=76, potassio_mg=250,
       zinco_mg=1.8, vit_b1_mg=0.4, vit_b3_mg=5, folato_ug=50),
    _f("Pão (papo-seco/carcaça)", "Pão e cereais", [("1 papo-seco", 50)],
       kcal=270, proteina_g=9, hidratos_g=53, gordura_g=1.5, fibra_g=3, sodio_mg=500,
       ferro_mg=2.5, magnesio_mg=30, vit_b1_mg=0.3, vit_b3_mg=3.5, folato_ug=90),
    _f("Tosta / pão torrado", "Pão e cereais", [("1 tosta", 15)],
       kcal=410, proteina_g=12, hidratos_g=72, gordura_g=7, fibra_g=5, sodio_mg=600, ferro_mg=3),
    _f("Arroz branco cozido", "Pão e cereais", [("1 concha", 90), ("Prato", 180)],
       kcal=130, proteina_g=2.7, hidratos_g=28, gordura_g=0.3, fibra_g=0.4, sodio_mg=1,
       magnesio_mg=12, potassio_mg=35, agua_ml=68),
    _f("Massa cozida", "Pão e cereais", [("Acompanhamento", 120), ("Prato", 200)],
       kcal=158, proteina_g=5.8, hidratos_g=31, gordura_g=0.9, fibra_g=1.8, sodio_mg=1,
       magnesio_mg=18, ferro_mg=1.3, folato_ug=18, agua_ml=62),
    _f("Aveia (flocos)", "Pão e cereais", [("3 colheres de sopa", 30), ("Taça", 50)],
       kcal=389, proteina_g=17, hidratos_g=66, gordura_g=7, gordura_saturada_g=1.2, fibra_g=10,
       acucar_g=1, magnesio_mg=177, ferro_mg=4.7, zinco_mg=4, potassio_mg=429, vit_b1_mg=0.76),
    _f("Cereais de pequeno-almoço (flocos de milho)", "Pão e cereais", [("Taça", 40)],
       kcal=378, proteina_g=7, hidratos_g=84, gordura_g=0.9, fibra_g=3, acucar_g=8, sodio_mg=520,
       ferro_mg=8, vit_b1_mg=1, vit_b2_mg=1.3, vit_b3_mg=15, vit_b6_mg=1.8, folato_ug=200, vit_b12_ug=2),
    _f("Batata cozida", "Pão e cereais", [("1 batata média", 150), ("Porção", 200)],
       kcal=87, proteina_g=1.9, hidratos_g=20, gordura_g=0.1, fibra_g=1.8, sodio_mg=4,
       potassio_mg=379, vit_c_mg=13, vit_b6_mg=0.3, magnesio_mg=22, agua_ml=77),
    _f("Batata frita (caseira)", "Pão e cereais", [("Porção", 150)],
       kcal=312, proteina_g=3.4, hidratos_g=41, gordura_g=15, gordura_saturada_g=2.3, fibra_g=3.8,
       sodio_mg=210, potassio_mg=580, vit_c_mg=9),

    # ---------- Proteínas ----------
    _f("Ovo", "Proteínas", [("1 ovo M", 55), ("1 ovo L", 65), ("2 ovos", 120)],
       kcal=143, proteina_g=13, hidratos_g=1.1, gordura_g=9.5, gordura_saturada_g=3.1, sodio_mg=142,
       calcio_mg=56, ferro_mg=1.8, zinco_mg=1.3, vit_a_ug=160, vit_d_ug=2, vit_e_mg=1,
       vit_b2_mg=0.46, vit_b12_ug=1.1, folato_ug=47),
    _f("Peito de frango grelhado", "Proteínas", [("1 peito pequeno", 120), ("Bife", 150)],
       kcal=165, proteina_g=31, gordura_g=3.6, gordura_saturada_g=1, sodio_mg=74, potassio_mg=256,
       magnesio_mg=29, zinco_mg=1, vit_b3_mg=13, vit_b6_mg=0.6, vit_b12_ug=0.3),
    _f("Bife de vaca", "Proteínas", [("Bife", 150)],
       kcal=217, proteina_g=26, gordura_g=12, gordura_saturada_g=5, sodio_mg=55, ferro_mg=2.6,
       zinco_mg=4.8, vit_b12_ug=2.6, vit_b3_mg=5, potassio_mg=330),
    _f("Carne de porco (lombo)", "Proteínas", [("Bife", 130)],
       kcal=242, proteina_g=27, gordura_g=14, gordura_saturada_g=5, sodio_mg=62, ferro_mg=0.9,
       zinco_mg=2, vit_b1_mg=0.9, vit_b6_mg=0.5, vit_b12_ug=0.7),
    _f("Hambúrguer de vaca", "Proteínas", [("1 hambúrguer", 100), ("1 hambúrguer grande", 150)],
       kcal=254, proteina_g=26, gordura_g=17, gordura_saturada_g=6.5, sodio_mg=75, ferro_mg=2.7,
       zinco_mg=6.2, potassio_mg=318, vit_b3_mg=5, vit_b6_mg=0.36, vit_b12_ug=2.6),
    _f("Hambúrguer de porco", "Proteínas", [("1 hambúrguer", 100), ("1 hambúrguer grande", 150)],
       kcal=297, proteina_g=25, gordura_g=21, gordura_saturada_g=7.8, sodio_mg=62, ferro_mg=1.2,
       zinco_mg=2.9, potassio_mg=362, vit_b1_mg=0.7, vit_b6_mg=0.4, vit_b12_ug=0.8),
    _f("Salmão", "Proteínas", [("Posta", 130)],
       kcal=208, proteina_g=20, gordura_g=13, gordura_saturada_g=3, omega3_g=2.3, sodio_mg=59,
       potassio_mg=363, vit_d_ug=11, vit_b12_ug=3.2, vit_b3_mg=8, magnesio_mg=27),
    _f("Atum em água (lata)", "Proteínas", [("1 lata escorrida", 80)],
       kcal=116, proteina_g=26, gordura_g=1, sodio_mg=320, potassio_mg=237, vit_d_ug=2,
       vit_b12_ug=2.5, vit_b3_mg=13, magnesio_mg=30, omega3_g=0.3),
    _f("Bacalhau cozido", "Proteínas", [("Posta", 150)],
       kcal=105, proteina_g=23, gordura_g=0.9, sodio_mg=320, potassio_mg=200, vit_b12_ug=1,
       magnesio_mg=30, omega3_g=0.2),
    _f("Sardinha", "Proteínas", [("3 sardinhas", 120)],
       kcal=208, proteina_g=25, gordura_g=11, gordura_saturada_g=1.5, omega3_g=1.5, calcio_mg=380,
       ferro_mg=2.9, vit_d_ug=4.8, vit_b12_ug=8.9, sodio_mg=307),
    _f("Camarão", "Proteínas", [("Porção", 100)],
       kcal=99, proteina_g=24, gordura_g=0.3, sodio_mg=111, calcio_mg=70, ferro_mg=0.5,
       zinco_mg=1.6, vit_b12_ug=1.1),
    _f("Fiambre de frango", "Proteínas", [("1 fatia", 20), ("2 fatias", 40)],
       kcal=110, proteina_g=18, gordura_g=3.5, gordura_saturada_g=1, sodio_mg=950, ferro_mg=0.8),

    # ---------- Lacticínios ----------
    _f("Leite meio-gordo", "Lacticínios", [("1 copo", 200), ("Chávena", 250)],
       kcal=47, proteina_g=3.3, hidratos_g=4.8, gordura_g=1.6, gordura_saturada_g=1, acucar_g=4.8,
       calcio_mg=120, potassio_mg=150, vit_b2_mg=0.18, vit_b12_ug=0.5, vit_d_ug=1.1, agua_ml=89),
    _f("Iogurte natural", "Lacticínios", [("1 iogurte", 125)],
       kcal=61, proteina_g=3.5, hidratos_g=4.7, gordura_g=3.3, gordura_saturada_g=2, acucar_g=4.7,
       calcio_mg=110, vit_b2_mg=0.14, vit_b12_ug=0.4, potassio_mg=155, agua_ml=88),
    _f("Queijo flamengo", "Lacticínios", [("1 fatia", 20)],
       kcal=350, proteina_g=25, gordura_g=27, gordura_saturada_g=17, sodio_mg=700, calcio_mg=720,
       vit_a_ug=250, vit_b12_ug=1.5, zinco_mg=3),
    _f("Requeijão", "Lacticínios", [("Porção", 100)],
       kcal=145, proteina_g=11, gordura_g=10, gordura_saturada_g=6, calcio_mg=90, sodio_mg=30, vit_a_ug=120),

    # ---------- Leguminosas ----------
    _f("Feijão cozido", "Leguminosas", [("Concha", 90), ("Porção", 130)],
       kcal=127, proteina_g=8.7, hidratos_g=22, gordura_g=0.5, fibra_g=6.4, sodio_mg=1, ferro_mg=2.9,
       magnesio_mg=45, potassio_mg=405, folato_ug=130, zinco_mg=1, agua_ml=63),
    _f("Grão-de-bico cozido", "Leguminosas", [("Concha", 90), ("Porção", 130)],
       kcal=164, proteina_g=8.9, hidratos_g=27, gordura_g=2.6, fibra_g=7.6, ferro_mg=2.9,
       magnesio_mg=48, potassio_mg=291, folato_ug=172, zinco_mg=1.5),
    _f("Lentilhas cozidas", "Leguminosas", [("Concha", 90), ("Porção", 130)],
       kcal=116, proteina_g=9, hidratos_g=20, gordura_g=0.4, fibra_g=7.9, ferro_mg=3.3,
       magnesio_mg=36, potassio_mg=369, folato_ug=181, zinco_mg=1.3),

    # ---------- Fruta ----------
    _f("Banana", "Fruta", [("1 banana", 120)],
       kcal=89, proteina_g=1.1, hidratos_g=23, gordura_g=0.3, fibra_g=2.6, acucar_g=12,
       potassio_mg=358, magnesio_mg=27, vit_c_mg=8.7, vit_b6_mg=0.37, folato_ug=20, agua_ml=75),
    _f("Maçã", "Fruta", [("1 maçã", 150)],
       kcal=52, proteina_g=0.3, hidratos_g=14, fibra_g=2.4, acucar_g=10, potassio_mg=107,
       vit_c_mg=4.6, agua_ml=86),
    _f("Laranja", "Fruta", [("1 laranja", 130)],
       kcal=47, proteina_g=0.9, hidratos_g=12, fibra_g=2.4, acucar_g=9, vit_c_mg=53,
       potassio_mg=181, calcio_mg=40, folato_ug=30, agua_ml=87),
    _f("Pera", "Fruta", [("1 pera", 150)],
       kcal=57, proteina_g=0.4, hidratos_g=15, fibra_g=3.1, acucar_g=10, potassio_mg=116,
       vit_c_mg=4.3, agua_ml=84),
    _f("Morangos", "Fruta", [("1 taça", 150)],
       kcal=32, proteina_g=0.7, hidratos_g=7.7, fibra_g=2, acucar_g=4.9, vit_c_mg=59,
       potassio_mg=153, folato_ug=24, agua_ml=91),
    _f("Uvas", "Fruta", [("1 cacho pequeno", 100)],
       kcal=69, proteina_g=0.7, hidratos_g=18, fibra_g=0.9, acucar_g=16, potassio_mg=191,
       vit_k_ug=14.6, agua_ml=81),
    _f("Kiwi", "Fruta", [("1 kiwi", 75)],
       kcal=61, proteina_g=1.1, hidratos_g=15, fibra_g=3, acucar_g=9, vit_c_mg=93, vit_k_ug=40,
       potassio_mg=312, agua_ml=83),
    _f("Melancia", "Fruta", [("1 fatia", 200)],
       kcal=30, proteina_g=0.6, hidratos_g=8, fibra_g=0.4, acucar_g=6, vit_c_mg=8, vit_a_ug=28,
       potassio_mg=112, agua_ml=91),

    # ---------- Vegetais ----------
    _f("Brócolos cozidos", "Vegetais", [("Porção", 100)],
       kcal=35, proteina_g=2.4, hidratos_g=7, fibra_g=3.3, vit_c_mg=65, vit_k_ug=141, folato_ug=108,
       potassio_mg=293, calcio_mg=40, vit_a_ug=77, agua_ml=89),
    _f("Espinafres cozidos", "Vegetais", [("Porção", 100)],
       kcal=23, proteina_g=3, hidratos_g=3.8, fibra_g=2.4, ferro_mg=3.6, magnesio_mg=87,
       potassio_mg=466, folato_ug=146, vit_a_ug=524, vit_k_ug=494, vit_c_mg=9.8, calcio_mg=136, agua_ml=91),
    _f("Cenoura", "Vegetais", [("1 cenoura", 80), ("Porção ralada", 60)],
       kcal=41, proteina_g=0.9, hidratos_g=10, fibra_g=2.8, acucar_g=4.7, vit_a_ug=835, vit_k_ug=13,
       potassio_mg=320, vit_c_mg=5.9, agua_ml=88),
    _f("Alface", "Vegetais", [("Porção", 50)],
       kcal=15, proteina_g=1.4, hidratos_g=2.9, fibra_g=1.3, vit_a_ug=370, vit_k_ug=126,
       folato_ug=38, potassio_mg=194, agua_ml=95),
    _f("Tomate", "Vegetais", [("1 tomate", 120)],
       kcal=18, proteina_g=0.9, hidratos_g=3.9, fibra_g=1.2, acucar_g=2.6, vit_c_mg=14, vit_a_ug=42,
       vit_k_ug=7.9, potassio_mg=237, agua_ml=94),
    _f("Couve cozida", "Vegetais", [("Porção", 100)],
       kcal=28, proteina_g=1.9, hidratos_g=5, fibra_g=2, vit_c_mg=35, vit_k_ug=400, folato_ug=60,
       calcio_mg=70, agua_ml=90),
    _f("Sopa de legumes", "Vegetais", [("1 prato", 300)],
       kcal=45, proteina_g=1.5, hidratos_g=7, gordura_g=1.5, fibra_g=2, potassio_mg=200, vit_a_ug=200,
       vit_c_mg=10, sodio_mg=300, agua_ml=88),

    # ---------- Gorduras e frutos secos ----------
    _f("Azeite", "Gorduras e frutos secos", [("1 fio", 7), ("1 colher de sopa", 14)],
       kcal=884, gordura_g=100, gordura_saturada_g=14, vit_e_mg=14, vit_k_ug=60),
    _f("Manteiga", "Gorduras e frutos secos", [("1 porção", 10)],
       kcal=717, proteina_g=0.9, gordura_g=81, gordura_saturada_g=51, sodio_mg=11, vit_a_ug=684, vit_d_ug=1.5),
    _f("Amêndoas", "Gorduras e frutos secos", [("Mão-cheia", 30)],
       kcal=579, proteina_g=21, hidratos_g=22, gordura_g=50, gordura_saturada_g=3.8, fibra_g=12.5,
       magnesio_mg=270, calcio_mg=269, ferro_mg=3.7, zinco_mg=3.1, vit_e_mg=25.6, potassio_mg=733),
    _f("Nozes", "Gorduras e frutos secos", [("Mão-cheia", 30)],
       kcal=654, proteina_g=15, hidratos_g=14, gordura_g=65, gordura_saturada_g=6, fibra_g=6.7,
       omega3_g=9, magnesio_mg=158, potassio_mg=441, zinco_mg=3),
    _f("Abacate", "Gorduras e frutos secos", [("Meio abacate", 100)],
       kcal=160, proteina_g=2, hidratos_g=9, gordura_g=15, gordura_saturada_g=2.1, fibra_g=6.7,
       potassio_mg=485, magnesio_mg=29, vit_e_mg=2.1, vit_k_ug=21, folato_ug=81, agua_ml=73),

    # ---------- Doces e snacks ----------
    _f("Bolo de chocolate", "Doces e snacks", [("1 fatia", 80)],
       kcal=371, proteina_g=5, hidratos_g=50, gordura_g=17, gordura_saturada_g=6, acucar_g=35,
       sodio_mg=320, ferro_mg=1.5, potassio_mg=180),
    _f("Chocolate de leite", "Doces e snacks", [("1 quadrado", 8), ("Meia tablete", 50)],
       kcal=535, proteina_g=7.6, hidratos_g=59, gordura_g=30, gordura_saturada_g=18, acucar_g=52,
       calcio_mg=189, magnesio_mg=63, ferro_mg=2.3),
    _f("Bolacha Maria", "Doces e snacks", [("2 bolachas", 16), ("4 bolachas", 32)],
       kcal=436, proteina_g=7, hidratos_g=75, gordura_g=11, gordura_saturada_g=4.5, acucar_g=22,
       sodio_mg=350, ferro_mg=2),
    _f("Batatas fritas de pacote", "Doces e snacks", [("Saco pequeno", 30)],
       kcal=536, proteina_g=6.6, hidratos_g=53, gordura_g=35, gordura_saturada_g=3.5, fibra_g=4.4,
       sodio_mg=525, potassio_mg=1000, vit_c_mg=31),
    _f("Croissant", "Doces e snacks", [("1 croissant", 60)],
       kcal=406, proteina_g=8, hidratos_g=46, gordura_g=21, gordura_saturada_g=12, acucar_g=11,
       sodio_mg=420, ferro_mg=2.3),
    _f("Pizza (queijo)", "Doces e snacks", [("1 fatia", 100)],
       kcal=266, proteina_g=11, hidratos_g=33, gordura_g=10, gordura_saturada_g=4.5, sodio_mg=600,
       calcio_mg=188, ferro_mg=2.5, potassio_mg=184),
    _f("Arroz doce", "Doces e snacks", [("Taça", 120)],
       kcal=150, proteina_g=3, hidratos_g=27, gordura_g=3, gordura_saturada_g=1.7, acucar_g=17,
       calcio_mg=90, agua_ml=60),
    _f("Mel", "Doces e snacks", [("1 colher de chá", 7), ("1 colher de sopa", 21)],
       kcal=304, hidratos_g=82, acucar_g=82, potassio_mg=52, calcio_mg=6, ferro_mg=0.42,
       magnesio_mg=2, vit_c_mg=0.5, agua_ml=17),

    # ---------- Bebidas ----------
    _f("Café expresso", "Bebidas", [("1 café (30 ml)", 30)],
       kcal=2, proteina_g=0.1, cafeina_mg=212, potassio_mg=115, agua_ml=97),
    _f("Café com leite", "Bebidas", [("1 chávena", 150)],
       kcal=30, proteina_g=1.6, gordura_g=1.2, calcio_mg=60, cafeina_mg=40, agua_ml=90),
    _f("Sumo de laranja natural", "Bebidas", [("1 copo", 200)],
       kcal=45, proteina_g=0.7, hidratos_g=10, acucar_g=8, vit_c_mg=50, potassio_mg=200,
       folato_ug=30, agua_ml=88),
    _f("Refrigerante (cola)", "Bebidas", [("1 lata", 330)],
       kcal=42, hidratos_g=10.6, acucar_g=10.6, sodio_mg=4, cafeina_mg=10, agua_ml=89),
    _f("Vinho tinto", "Bebidas", [("1 copo", 150)],
       kcal=85, hidratos_g=2.6, acucar_g=0.6, potassio_mg=127, agua_ml=86),
    _f("Cerveja", "Bebidas", [("1 imperial", 200), ("1 caneca", 330)],
       kcal=43, proteina_g=0.5, hidratos_g=3.6, potassio_mg=27, agua_ml=92),
    _f("Água", "Bebidas", [("1 copo", 200), ("1 garrafa", 500)],
       kcal=0, agua_ml=100),

    # ---------- Sopas e pratos típicos portugueses ----------
    _f("Caldo verde", "Sopas e pratos", [("1 tigela", 300)],
       kcal=50, proteina_g=2, hidratos_g=7, gordura_g=1.5, fibra_g=1.5, sodio_mg=300,
       potassio_mg=250, vit_a_ug=120, vit_c_mg=25, vit_k_ug=180, agua_ml=88),
    _f("Canja de galinha", "Sopas e pratos", [("1 tigela", 300)],
       kcal=45, proteina_g=3.5, hidratos_g=5, gordura_g=1, sodio_mg=320, potassio_mg=120,
       vit_b3_mg=2, agua_ml=90),
    _f("Creme de legumes", "Sopas e pratos", [("1 tigela", 300)],
       kcal=55, proteina_g=1.6, hidratos_g=8, gordura_g=2, fibra_g=2, sodio_mg=280,
       potassio_mg=230, vit_a_ug=300, vit_c_mg=12, agua_ml=87),
    _f("Sopa de abóbora", "Sopas e pratos", [("1 tigela", 300)],
       kcal=45, proteina_g=1.3, hidratos_g=8, gordura_g=1.2, fibra_g=1.8, sodio_mg=260,
       potassio_mg=240, vit_a_ug=450, vit_c_mg=8, agua_ml=89),
    _f("Sopa de feijão verde", "Sopas e pratos", [("1 tigela", 300)],
       kcal=58, proteina_g=2.5, hidratos_g=9, gordura_g=1.5, fibra_g=2.5, sodio_mg=270,
       ferro_mg=1, potassio_mg=260, vit_c_mg=10, agua_ml=87),
    _f("Açorda alentejana", "Sopas e pratos", [("1 prato", 250)],
       kcal=95, proteina_g=3.5, hidratos_g=14, gordura_g=2.8, fibra_g=1, sodio_mg=400,
       agua_ml=78),
    _f("Caldeirada de peixe", "Sopas e pratos", [("1 prato", 350)],
       kcal=110, proteina_g=11, hidratos_g=7, gordura_g=4, sodio_mg=350, potassio_mg=350,
       vit_b12_ug=1.5, omega3_g=0.4, agua_ml=78),
    _f("Bacalhau à Brás", "Sopas e pratos", [("1 prato", 300)],
       kcal=180, proteina_g=12, hidratos_g=12, gordura_g=9, gordura_saturada_g=2.2, sodio_mg=420,
       potassio_mg=230, vit_b12_ug=1.2, vit_a_ug=70, agua_ml=62),
    _f("Bacalhau com natas", "Sopas e pratos", [("1 prato", 300)],
       kcal=200, proteina_g=11, hidratos_g=14, gordura_g=11, gordura_saturada_g=5, sodio_mg=450,
       calcio_mg=120, vit_b12_ug=1, agua_ml=60),
    _f("Bacalhau à Gomes de Sá", "Sopas e pratos", [("1 prato", 300)],
       kcal=165, proteina_g=13, hidratos_g=13, gordura_g=8, gordura_saturada_g=1.8, sodio_mg=430,
       potassio_mg=300, vit_b12_ug=1.1, agua_ml=64),
    _f("Francesinha", "Sopas e pratos", [("1 francesinha", 350)],
       kcal=280, proteina_g=15, hidratos_g=18, gordura_g=16, gordura_saturada_g=7, sodio_mg=620,
       calcio_mg=120, ferro_mg=2, agua_ml=48),
    _f("Bifana (sande)", "Sopas e pratos", [("1 bifana", 150)],
       kcal=220, proteina_g=14, hidratos_g=24, gordura_g=8, gordura_saturada_g=2.5, sodio_mg=520,
       ferro_mg=1.8, agua_ml=40),
    _f("Prego (sande)", "Sopas e pratos", [("1 prego", 160)],
       kcal=235, proteina_g=16, hidratos_g=23, gordura_g=9, gordura_saturada_g=3, sodio_mg=500,
       ferro_mg=2.2, zinco_mg=2, agua_ml=40),
    _f("Arroz de pato", "Sopas e pratos", [("1 prato", 300)],
       kcal=185, proteina_g=9, hidratos_g=22, gordura_g=6.5, gordura_saturada_g=2, sodio_mg=380,
       ferro_mg=1.5, vit_b12_ug=0.6, agua_ml=58),
    _f("Arroz de marisco", "Sopas e pratos", [("1 prato", 350)],
       kcal=130, proteina_g=7, hidratos_g=18, gordura_g=3, sodio_mg=400, potassio_mg=180,
       zinco_mg=1.2, vit_b12_ug=2, agua_ml=68),
    _f("Cozido à portuguesa", "Sopas e pratos", [("1 prato", 350)],
       kcal=170, proteina_g=12, hidratos_g=9, gordura_g=10, gordura_saturada_g=4, sodio_mg=480,
       ferro_mg=2.2, zinco_mg=2.5, vit_b12_ug=1.5, potassio_mg=300, agua_ml=66),
    _f("Feijoada à transmontana", "Sopas e pratos", [("1 prato", 300)],
       kcal=165, proteina_g=10, hidratos_g=14, gordura_g=8, gordura_saturada_g=3, fibra_g=5,
       ferro_mg=2.8, potassio_mg=380, folato_ug=90, agua_ml=64),
    _f("Jardineira (carne guisada)", "Sopas e pratos", [("1 prato", 300)],
       kcal=130, proteina_g=8, hidratos_g=13, gordura_g=5, fibra_g=2.5, sodio_mg=360,
       potassio_mg=330, vit_a_ug=200, vit_c_mg=10, agua_ml=72),
    _f("Bitoque (bife, ovo, batata, arroz)", "Sopas e pratos", [("1 prato", 350)],
       kcal=200, proteina_g=13, hidratos_g=16, gordura_g=9, gordura_saturada_g=3, sodio_mg=420,
       ferro_mg=2, zinco_mg=2.2, vit_b12_ug=1, agua_ml=58),
    _f("Frango assado", "Sopas e pratos", [("1 quarto", 200)],
       kcal=190, proteina_g=25, hidratos_g=0, gordura_g=10, gordura_saturada_g=2.8, sodio_mg=300,
       potassio_mg=250, vit_b3_mg=10, vit_b6_mg=0.5, agua_ml=60),
    _f("Carne de porco à alentejana", "Sopas e pratos", [("1 prato", 300)],
       kcal=180, proteina_g=14, hidratos_g=12, gordura_g=9, gordura_saturada_g=3, sodio_mg=450,
       zinco_mg=2, vit_b1_mg=0.5, vit_b12_ug=1.2, agua_ml=62),
    _f("Rojões", "Sopas e pratos", [("1 prato", 200)],
       kcal=250, proteina_g=20, gordura_g=18, gordura_saturada_g=6, sodio_mg=380, ferro_mg=1.2,
       zinco_mg=2.5, vit_b1_mg=0.7, agua_ml=52),
    _f("Polvo à lagareiro", "Sopas e pratos", [("1 prato", 250)],
       kcal=140, proteina_g=14, hidratos_g=6, gordura_g=7, sodio_mg=420, ferro_mg=3,
       zinco_mg=1.7, vit_b12_ug=20, agua_ml=70),
    _f("Migas", "Sopas e pratos", [("1 porção", 200)],
       kcal=200, proteina_g=5, hidratos_g=25, gordura_g=9, fibra_g=2, sodio_mg=420, agua_ml=58),
    _f("Omelete (2 ovos)", "Sopas e pratos", [("1 omelete", 120)],
       kcal=154, proteina_g=11, gordura_g=12, gordura_saturada_g=3.4, sodio_mg=180, calcio_mg=55,
       ferro_mg=1.7, vit_a_ug=150, vit_b12_ug=1, vit_d_ug=2, agua_ml=72),
    _f("Pataniscas de bacalhau", "Sopas e pratos", [("2 pataniscas", 120)],
       kcal=230, proteina_g=10, hidratos_g=18, gordura_g=13, gordura_saturada_g=2, sodio_mg=450,
       vit_b12_ug=0.8, agua_ml=50),
    _f("Pastel de bacalhau", "Sopas e pratos", [("1 pastel", 60)],
       kcal=220, proteina_g=9, hidratos_g=16, gordura_g=13, gordura_saturada_g=2.5, sodio_mg=430,
       agua_ml=52),
    _f("Rissol de carne", "Sopas e pratos", [("1 rissol", 50)],
       kcal=280, proteina_g=8, hidratos_g=26, gordura_g=16, gordura_saturada_g=4, sodio_mg=450),
    _f("Croquete de carne", "Sopas e pratos", [("1 croquete", 50)],
       kcal=275, proteina_g=9, hidratos_g=22, gordura_g=16, gordura_saturada_g=4, sodio_mg=460,
       ferro_mg=1.5),
    _f("Lasanha", "Sopas e pratos", [("1 fatia", 250)],
       kcal=170, proteina_g=9, hidratos_g=16, gordura_g=8, gordura_saturada_g=4, sodio_mg=380,
       calcio_mg=120, ferro_mg=1.5, agua_ml=62),
    _f("Esparguete à bolonhesa", "Sopas e pratos", [("1 prato", 300)],
       kcal=150, proteina_g=8, hidratos_g=20, gordura_g=4.5, fibra_g=2, sodio_mg=320,
       ferro_mg=1.5, potassio_mg=250, agua_ml=66),
    _f("Caril de frango", "Sopas e pratos", [("1 prato", 300)],
       kcal=150, proteina_g=14, hidratos_g=8, gordura_g=7, gordura_saturada_g=2.5, sodio_mg=380,
       vit_b3_mg=7, potassio_mg=260, agua_ml=68),

    # ---------- Sobremesas portuguesas ----------
    _f("Pastel de nata", "Doces e snacks", [("1 pastel", 50)],
       kcal=298, proteina_g=5, hidratos_g=37, gordura_g=14, gordura_saturada_g=6, acucar_g=22,
       calcio_mg=70, vit_a_ug=90),
    _f("Bola de Berlim", "Doces e snacks", [("1 bola", 90)],
       kcal=330, proteina_g=6, hidratos_g=45, gordura_g=14, gordura_saturada_g=4, acucar_g=20,
       sodio_mg=200, ferro_mg=1.5),
    _f("Leite-creme", "Doces e snacks", [("1 taça", 120)],
       kcal=150, proteina_g=4, hidratos_g=22, gordura_g=5, gordura_saturada_g=2.5, acucar_g=18,
       calcio_mg=110, agua_ml=64),
    _f("Pudim flan", "Doces e snacks", [("1 fatia", 120)],
       kcal=150, proteina_g=4, hidratos_g=26, gordura_g=3.5, acucar_g=24, calcio_mg=90, agua_ml=62),
    _f("Mousse de chocolate", "Doces e snacks", [("1 taça", 100)],
       kcal=230, proteina_g=4, hidratos_g=25, gordura_g=13, gordura_saturada_g=7, acucar_g=22,
       calcio_mg=40, ferro_mg=1.5),
    _f("Bolo de bolacha", "Doces e snacks", [("1 fatia", 100)],
       kcal=380, proteina_g=5, hidratos_g=40, gordura_g=22, gordura_saturada_g=10, acucar_g=28,
       sodio_mg=200),
    _f("Salame de chocolate", "Doces e snacks", [("1 fatia", 60)],
       kcal=480, proteina_g=6, hidratos_g=45, gordura_g=30, gordura_saturada_g=16, acucar_g=35,
       ferro_mg=2),
    _f("Aletria", "Doces e snacks", [("1 porção", 120)],
       kcal=170, proteina_g=4, hidratos_g=30, gordura_g=4, acucar_g=18, calcio_mg=70, agua_ml=58),
    _f("Sonhos", "Doces e snacks", [("2 sonhos", 60)],
       kcal=360, proteina_g=6, hidratos_g=40, gordura_g=19, gordura_saturada_g=4, acucar_g=15),
    _f("Queijada", "Doces e snacks", [("1 queijada", 60)],
       kcal=350, proteina_g=7, hidratos_g=45, gordura_g=15, gordura_saturada_g=8, acucar_g=28,
       calcio_mg=80),
    _f("Tarte de maçã", "Doces e snacks", [("1 fatia", 110)],
       kcal=260, proteina_g=3, hidratos_g=35, gordura_g=12, gordura_saturada_g=5, acucar_g=20,
       fibra_g=1.5),
    _f("Toucinho-do-céu", "Doces e snacks", [("1 fatia", 80)],
       kcal=380, proteina_g=8, hidratos_g=42, gordura_g=20, gordura_saturada_g=4, acucar_g=38),
    _f("Bolo-rei", "Doces e snacks", [("1 fatia", 80)],
       kcal=330, proteina_g=6, hidratos_g=48, gordura_g=12, gordura_saturada_g=4, acucar_g=24,
       sodio_mg=180),
    _f("Gelado (baunilha)", "Doces e snacks", [("1 bola", 60)],
       kcal=207, proteina_g=3.5, hidratos_g=24, gordura_g=11, gordura_saturada_g=7, acucar_g=21,
       calcio_mg=128, agua_ml=61),

    # ---------- Mais pão típico ----------
    _f("Broa de milho", "Pão e cereais", [("1 fatia", 50)],
       kcal=250, proteina_g=6, hidratos_g=50, gordura_g=2.5, fibra_g=4, sodio_mg=450,
       ferro_mg=1.5, magnesio_mg=40),
    _f("Tosta mista", "Pão e cereais", [("1 tosta mista", 150)],
       kcal=280, proteina_g=14, hidratos_g=28, gordura_g=12, gordura_saturada_g=6, sodio_mg=700,
       calcio_mg=200, vit_b12_ug=0.8),

    # ---------- Mais lacticínios e queijos ----------
    _f("Queijo curado (ovelha)", "Lacticínios", [("1 fatia", 25), ("1 porção", 50)],
       kcal=380, proteina_g=26, gordura_g=30, gordura_saturada_g=19, sodio_mg=700, calcio_mg=800,
       vit_a_ug=280, vit_b12_ug=1.5, zinco_mg=3.5),
    _f("Queijo da Serra", "Lacticínios", [("1 porção", 30)],
       kcal=360, proteina_g=22, gordura_g=29, gordura_saturada_g=18, sodio_mg=600, calcio_mg=600,
       vit_a_ug=250, vit_b12_ug=1.2),
    _f("Queijo de cabra", "Lacticínios", [("1 fatia", 30)],
       kcal=360, proteina_g=22, gordura_g=30, gordura_saturada_g=20, sodio_mg=520, calcio_mg=300,
       vit_a_ug=290, vit_b12_ug=0.6),
    _f("Queijo fresco", "Lacticínios", [("1 queijo fresco", 100)],
       kcal=110, proteina_g=11, gordura_g=7, gordura_saturada_g=4, sodio_mg=300, calcio_mg=90,
       vit_b12_ug=0.5, agua_ml=72),
    _f("Queijo mozzarella", "Lacticínios", [("1 porção", 30), ("1 bola", 125)],
       kcal=280, proteina_g=22, gordura_g=22, gordura_saturada_g=13, sodio_mg=480, calcio_mg=500,
       vit_b12_ug=1, vit_a_ug=180),
    _f("Queijo parmesão (ralado)", "Lacticínios", [("1 colher de sopa", 10)],
       kcal=392, proteina_g=36, gordura_g=29, gordura_saturada_g=19, sodio_mg=1200, calcio_mg=1180,
       vit_a_ug=200, vit_b12_ug=1.2, zinco_mg=2.8),
    _f("Queijo creme (tipo Philadelphia)", "Lacticínios", [("1 porção", 30)],
       kcal=250, proteina_g=6, gordura_g=24, gordura_saturada_g=15, sodio_mg=320, calcio_mg=100,
       vit_a_ug=200),
    _f("Iogurte grego", "Lacticínios", [("1 iogurte", 150)],
       kcal=97, proteina_g=9, hidratos_g=4, gordura_g=5, gordura_saturada_g=3, calcio_mg=100,
       vit_b12_ug=0.5, agua_ml=85),
    _f("Iogurte magro", "Lacticínios", [("1 iogurte", 125)],
       kcal=56, proteina_g=5, hidratos_g=7.5, gordura_g=0.1, acucar_g=7, calcio_mg=120,
       vit_b2_mg=0.2, vit_b12_ug=0.4, agua_ml=85),
    _f("Kefir", "Lacticínios", [("1 copo", 200)],
       kcal=55, proteina_g=3.3, hidratos_g=4.5, gordura_g=3, calcio_mg=120, vit_b12_ug=0.4,
       vit_b2_mg=0.2, agua_ml=88),
    _f("Leite gordo", "Lacticínios", [("1 copo", 200), ("Chávena", 250)],
       kcal=64, proteina_g=3.2, hidratos_g=4.8, gordura_g=3.6, gordura_saturada_g=2.3, acucar_g=4.8,
       calcio_mg=120, vit_b12_ug=0.5, vit_d_ug=1, vit_a_ug=46, agua_ml=88),
    _f("Leite magro", "Lacticínios", [("1 copo", 200)],
       kcal=35, proteina_g=3.4, hidratos_g=5, gordura_g=0.1, acucar_g=5, calcio_mg=122,
       vit_b12_ug=0.5, agua_ml=90),
    _f("Bebida de aveia", "Lacticínios", [("1 copo", 200)],
       kcal=45, proteina_g=1, hidratos_g=7, gordura_g=1.5, fibra_g=0.8, calcio_mg=120,
       vit_d_ug=1.5, vit_b12_ug=0.4, agua_ml=90),
    _f("Natas (para cozinhar)", "Lacticínios", [("1 colher de sopa", 15)],
       kcal=290, proteina_g=2.5, hidratos_g=3, gordura_g=30, gordura_saturada_g=19, calcio_mg=80,
       vit_a_ug=280),

    # ---------- Molhos e temperos ----------
    _f("Maionese", "Molhos e temperos", [("1 colher de sopa", 15)],
       kcal=680, gordura_g=75, gordura_saturada_g=11, sodio_mg=600, vit_k_ug=100),
    _f("Maionese light", "Molhos e temperos", [("1 colher de sopa", 15)],
       kcal=300, gordura_g=28, gordura_saturada_g=4, sodio_mg=600),
    _f("Ketchup", "Molhos e temperos", [("1 colher de sopa", 15)],
       kcal=110, hidratos_g=26, acucar_g=22, sodio_mg=900, vit_c_mg=4, vit_a_ug=30, potassio_mg=280),
    _f("Mostarda", "Molhos e temperos", [("1 colher de chá", 5)],
       kcal=66, proteina_g=4, hidratos_g=5, gordura_g=3.5, sodio_mg=1100, calcio_mg=60),
    _f("Molho barbecue", "Molhos e temperos", [("1 colher de sopa", 17)],
       kcal=170, hidratos_g=40, acucar_g=33, sodio_mg=1000, potassio_mg=230),
    _f("Molho béchamel", "Molhos e temperos", [("1 concha", 60)],
       kcal=150, proteina_g=4, hidratos_g=11, gordura_g=10, gordura_saturada_g=6, calcio_mg=110,
       sodio_mg=400, agua_ml=70),
    _f("Molho de soja", "Molhos e temperos", [("1 colher de sopa", 15)],
       kcal=60, proteina_g=8, hidratos_g=5, sodio_mg=5500, agua_ml=70),
    _f("Pesto", "Molhos e temperos", [("1 colher de sopa", 15)],
       kcal=450, proteina_g=5, gordura_g=45, gordura_saturada_g=7, sodio_mg=800, calcio_mg=120,
       vit_k_ug=80),
    _f("Molho de tomate (polpa)", "Molhos e temperos", [("1 concha", 60)],
       kcal=35, proteina_g=1.5, hidratos_g=6, fibra_g=1.5, acucar_g=4, sodio_mg=300, potassio_mg=300,
       vit_c_mg=10, vit_a_ug=40, agua_ml=88),
    _f("Vinagre", "Molhos e temperos", [("1 colher de sopa", 15)],
       kcal=20, hidratos_g=0.6, sodio_mg=2, agua_ml=94),

    # ---------- Mais vegetais (imunidade) ----------
    _f("Cebola", "Vegetais", [("1 cebola média", 110), ("1 colher (picada)", 15)],
       kcal=40, proteina_g=1.1, hidratos_g=9, fibra_g=1.7, acucar_g=4.2, vit_c_mg=7.4,
       potassio_mg=146, folato_ug=19, vit_b6_mg=0.12, agua_ml=89),
    _f("Alho", "Vegetais", [("1 dente", 5), ("3 dentes", 15)],
       kcal=149, proteina_g=6.4, hidratos_g=33, fibra_g=2.1, vit_c_mg=31, potassio_mg=401,
       calcio_mg=181, magnesio_mg=25, zinco_mg=1.2, vit_b6_mg=1.2, agua_ml=59),
    _f("Pimento", "Vegetais", [("1 pimento", 120)],
       kcal=31, proteina_g=1, hidratos_g=6, fibra_g=2.1, acucar_g=4.2, vit_c_mg=128, vit_a_ug=157,
       vit_b6_mg=0.3, potassio_mg=211, folato_ug=46, agua_ml=92),
]


def categorias() -> list[str]:
    presentes = {a["categoria"] for a in ALIMENTOS}
    return [c for c in CATEGORIAS if c in presentes]


def por_categoria(categoria: str) -> list[dict]:
    return [a for a in ALIMENTOS if a["categoria"] == categoria]
